### ISSUE TITLE
Whats scope?

### ISSUE THREAD

**Issue by r-bt** [NoahVersace/svelte-notion#7]
Hey,

Really like the new name :) Just wondering what `scope` is as I'm getting the error `this.scope.includes is not a function` sometimes.

**Comment by noahsalvi** [comment]
Haha thanks :)

The scope is the "current table" from which slugPage will read.

For example:
https://github.com/noahsalvi/sotion-sapper-demo/blob/master/src/routes/_layout.svelte
In this file I set the scope by setting the id of this [table](https://www.notion.so/765b1258c01c4c8caae4120790e4805a?v=a474cc2c52bc415881217696e1e0b781).

Having done that I can now access the pages of the table by only passing the slug (slugPage) instead of needing to lookup the id myself. Just make sure to set the scope before using slugPage. In this example setScope will be executed first since it is in the _layout.svelte file.


https://github.com/noahsalvi/sotion-sapper-demo/blob/master/src/routes/%5Bslug%5D.svelte
`sotion.slugPage(params.slug);`
As you see I can just pass the slug, which is set by the params of the current route and it will then check for it in the "scoped" table and get its id and call it.

If you already know the exact slug of the page for example "code" you can also run sotion.slugPage("code");

slugPage also returns "meta", which is basically just all the fields of the "slugged" column in a json format.

**Comment by r-bt** [comment]
Awesome! I just got it set up there and it works great :) I had set something up before to get pretty urls with slugs working but it's even better to have it built into the library.
